---
- hosts: all
  become: yes
  become_user: root
  vars_files:
    - creds.yml
    - stack_data.yaml
  
  tasks:
  - name: Install pip3
    apt:
      pkg: python3-pip
      state: present
      update_cache: true

  - name: "Install python libraries"
    pip:
      name: ['docker-py']
      state: latest
    tags:
      - always

  - name: Install docker
    apt: 
      pkg: docker.io
      state: present
      update_cache: true
    register: docker_started
    notify: Enable docker
  
  - name: Start webapp container
    docker_container:
      name: webapp
      image: mmadraimov/webapp:v1.0
      state: started
      restart_policy: unless-stopped
      ports:
      - "8000:8000"
      env:
          SERVER: "{{ PostgresDNS }}"
          USER: "{{ db_master_username }}"
          PASSWORD: "{{ db_master_password }}"
    when: docker_started is success

  - debug: 
      msg:
      - "Webapp link: {{ELBPublicDNS}}"
      - "SSH access ip: {{WebappEC2IP}}"

  handlers:
  - name: Enable docker
    service:
      name: docker
      enabled: true