language: go

go:
  - "1.x"

services:
  - docker

stages:
  - webapp
  - docker

jobs:
  include:
    - stage: webapp
      before_install:
        - cd ./web-app
      install:
        - make deps
      script:
        - make build

    - stage: docker
      before_install:
        - cd ./web-app
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      script:
        - docker build -t ${DOCKER_USERNAME}/webapp:latest .
        - docker push ${DOCKER_USERNAME}/webapp:latest
