language: go

go:
  - "1.x"

services:
  - docker

jobs:
  include:
      before_install:
        - cd ./web-app
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      install:
        - make deps
      script:
        - make build
        - docker build -t ${DOCKER_USERNAME}/webapp:latest .
        - docker push ${DOCKER_USERNAME}/webapp:latest
