language: go

go:
  - "1.x"

services:
  - docker

before_install:
  - cd ./web-app

after_install:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker build -t ${DOCKER_USERNAME}/webapp:latest .
  - docker push ${DOCKER_USERNAME}/webapp:latest
