---
# tasks file for cleanup
- name: delete a template ec2 instance
  cloudformation:
    stack_name: "{{template_name}}"
    aws_access_key: "{{aws_access_key}}"
    aws_secret_key: "{{aws_secret_key}}"
    region: "{{aws_region}}"
    state: "absent"
  register: webapp_deleted