---
# tasks file for infra
- name: Create infrastructure network
  cloudformation:
    stack_name: "{{network_stack_name}}"
    state: "present"
    region: "{{aws_region}}"
    aws_access_key: "{{aws_access_key}}"
    aws_secret_key: "{{aws_secret_key}}"
    template: "cloudformation/network.json"
  register: aws_network_stack