network_stack_name: "wallester-test-network"
database_stack_name: "wallester-test-database"
webapp_stack_name: "wallester-test-webapp"

aws_region: eu-west-1 # Ireland
ec2_keypair: keypair
instance_type: t2.micro
volumes:
  - device_name: /dev/sda1
    volume_type: gp2
    volume_size: 20
    delete_on_termination: true
